@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}


### signup user

POST http://{{host}}/api/signup  HTTP/1.1
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Tyr Chen",
    "email": "tchen@acme.org",
    "password": "123456"
}

### signup user

POST http://{{host}}/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456"
}



### signin user (invalid)

# @name signin
POST http://{{host}}/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "1234567"
}

### signin user (valid)

# @name signin
POST http://{{host}}/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### create chat
POST http://{{host}}/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2, 1, 2],
    "public": false
}

### upload files

POST http://{{host}}/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="demo.png"
Content-Type: application/octet-stream

< /root/workspace/rust/chat/chat_server/assets/demo.jpg
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--


### get png file

GET http://{{host}}/api/files/1/8ab/d00/a3253d525b37958381ba1cb044d1cad887.png
Authorization: Bearer {{token}}


### get text file
GET http://{{host}}/api/files/1/0a0/a9f/2a6772942557ab5355d76af442f8f65e01.txt
Authorization: Bearer {{token}}

### send a message
